GET http://localhost:3001/api/filmovi
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvc2lwYSIsImlkIjoiNjIxZmEwZGUyOWExZGY2ODUxMDI1Mjg5IiwiaWF0IjoxNjQ2Mjk5ODQ4fQ.6kpA5lu0PCabPEbuY3HC1fypOkkgAvP8aeNSYrpGqU4